import numpy as np
from pathlib import Path

class Data():
    def __init__(self):
        ...

    def LoadData(self):
        ...

    def SaveData(self):
        ...

    def PassData(self, data):
        ...

    def Flip_Data_lr(self):
        ...
    def Flip_Data_ud(self):
        ...
    def Rotate_Data_cw(self):
        ...
    def Rotate_Data_acw(self):
        ...